package com.daham.core.domain;

public enum SensorType {
  SENSOR_DEFAULT,
  SENSOR_TEMPERATURE_INSIDE,
  SENSOR_TEMPERATURE_OUTSIDE,
  SENSOR_HUMIDITY_INSIDE,
  SENSOR_HUMIDITY_OUTSIDE,
  SENSOR_WEIGHT,
}
