services:
  mariadb1:
    image: mariadb:11.8
    container_name: mariadb1
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=${MARIADB1_ALLOW_EMPTY_ROOT_PASSWORD:-false}
      - MARIADB_DATABASE=${MARIADB1_DATABASE:-master_schema}
      - MARIADB_USER=${MARIADB1_USER:-mariadb}
      - MARIADB_PASSWORD=${MARIADB1_PASSWORD:-Passme1234!}
      - MARIADB_ROOT_PASSWORD=${MARIADB1_ROOT_PASSWORD:-Passme1234!}
    volumes:
      - mariadb1-storage:/var/lib/mysql
      - ./mariadb1/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - shared-network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  mariadb2:
    image: mariadb:11.8
    container_name: mariadb2
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=${MARIADB2_ALLOW_EMPTY_ROOT_PASSWORD:-false}
      - MARIADB_DATABASE=${MARIADB2_DATABASE:-data_schema}
      - MARIADB_USER=${MARIADB2_USER:-mariadb}
      - MARIADB_PASSWORD=${MARIADB2_PASSWORD:-Passme1234!}
      - MARIADB_ROOT_PASSWORD=${MARIADB2_ROOT_PASSWORD:-Passme1234!}
    volumes:
      - mariadb2-storage:/var/lib/mysql
      - ./mariadb2/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - shared-network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  prometheus:
    image: prom/prometheus:v3.4.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus/config-prod.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - shared-network

  grafana:
    image: grafana/grafana:9.1.7
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - GF_USERS_ALLOW_SIGN_UP=${GRAFANA_ALLOW_SIGN_UP:-false}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-grafana}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-Passme1234!}
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - shared-network
    depends_on:
      - prometheus

  consul:
    image: consul:1.7
    container_name: consul
    command: agent -dev -ui -client=0.0.0.0 -bind=0.0.0.0 --https-port=8501
    ports:
      - "8500:8500"
      - "8501:8501"
    restart: unless-stopped
    networks:
      - shared-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8500/v1/status/leader" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME:-rabbitmq}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-Passme1234!}
    volumes:
      - rabbitmq-storage:/var/lib/rabbitmq
    networks:
      - shared-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  core-service:
    build:
      context: ../core-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: core-service
    restart: unless-stopped
    ports:
      - '8081:8081'
    depends_on:
      consul:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mariadb1:
        condition: service_healthy
    environment:
      - QUARKUS_PROFILE=prod
      - QUARKUS_HTTP_PORT=8081
      - DATABASE_USERNAME=${MARIADB1_USER:-mariadb}
      - DATABASE_PASSWORD=${MARIADB1_PASSWORD:-Passme1234!}
      - DATABASE_URL=jdbc:mariadb://mariadb1:3306/${MARIADB1_DATABASE:-master_schema}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME:-rabbitmq}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-Passme1234!}
      - CONSUL_HOST=consul
      - CONSUL_HEALTH_CHECK_HOST=core-service
    networks:
      - shared-network

  data-analysis-service:
    build:
      context: ../data-analysis-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: data-analysis-service
    restart: unless-stopped
    ports:
      - '8082:8082'
    depends_on:
      consul:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mariadb2:
        condition: service_healthy
    environment:
      - QUARKUS_PROFILE=prod
      - QUARKUS_HTTP_PORT=8082
      - DATABASE_USERNAME=${MARIADB2_USER:-mariadb}
      - DATABASE_PASSWORD=${MARIADB2_PASSWORD:-Passme1234!}
      - DATABASE_URL=jdbc:mariadb://mariadb2:3306/${MARIADB2_DATABASE:-data_schema}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME:-rabbitmq}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-Passme1234!}
      - CONSUL_HOST=consul
      - CONSUL_HEALTH_CHECK_HOST=data-analysis-service
    networks:
      - shared-network

  data-collector-service1:
    build:
      context: ../data-collector-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: data-collector-service1
    restart: unless-stopped
    ports:
      - '8083:8083'
    depends_on:
      consul:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      data-analysis-service:
        condition: service_started
    environment:
      - QUARKUS_PROFILE=prod
      - QUARKUS_HTTP_PORT=8083
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME:-rabbitmq}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-Passme1234!}
      - CONSUL_HOST=consul
      - CONSUL_HEALTH_CHECK_HOST=data-collector-service1
    networks:
      - shared-network

  data-collector-service2:
    build:
      context: ../data-collector-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: data-collector-service2
    restart: unless-stopped
    ports:
      - '8084:8084'
    depends_on:
      consul:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      data-analysis-service:
        condition: service_started
    environment:
      - QUARKUS_PROFILE=prod
      - QUARKUS_HTTP_PORT=8084
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME:-rabbitmq}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-Passme1234!}
      - CONSUL_HOST=consul
      - CONSUL_HEALTH_CHECK_HOST=data-collector-service2
    networks:
      - shared-network

  gateway-service:
    build:
      context: ../gateway-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: gateway-service
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      consul:
        condition: service_healthy
      core-service:
        condition: service_started
      data-analysis-service:
        condition: service_started
      data-collector-service1:
        condition: service_started
      data-collector-service2:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_HEALTH_CHECK_HOST=gateway-service
      - SPRING_APPLICATION_NAME=gateway-service
      - SERVER_PORT=8080
    networks:
      - shared-network

  data-producer-service:
    build:
      context: ../data-producer-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: data-producer-service
    restart: unless-stopped
    depends_on:
      gateway-service:
        condition: service_started
    environment:
      - DATABASE_USERNAME=${H2_USERNAME:-h2}
      - DATABASE_PASSWORD=${H2_PASSWORD:-Passme1234!}
      - DATA_COLLECTOR_SERVICE_URL=http://gateway-service:8080
    networks:
      - shared-network

volumes:
  mariadb1-storage:
  mariadb2-storage:
  prometheus-storage:
  grafana-storage:
  rabbitmq-storage:

networks:
  shared-network:
    driver: bridge